# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate rust-ini

Name:           rust-rust-ini0.20
Version:        0.20.0
Release:        %autorelease
Summary:        Ini configuration file parsing library in Rust

License:        MIT
URL:            https://crates.io/crates/rust-ini
Source:         %{crates_source}

Patch: downgrade-ordered-multimap.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An Ini configuration file parsing library in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+brackets-in-section-names-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brackets-in-section-names-devel %{_description}

This package contains library source intended for building other packages which
use the "brackets-in-section-names" feature of the "%{crate}" crate.

%files       -n %{name}+brackets-in-section-names-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+case-insensitive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+case-insensitive-devel %{_description}

This package contains library source intended for building other packages which
use the "case-insensitive" feature of the "%{crate}" crate.

%files       -n %{name}+case-insensitive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+inline-comment-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+inline-comment-devel %{_description}

This package contains library source intended for building other packages which
use the "inline-comment" feature of the "%{crate}" crate.

%files       -n %{name}+inline-comment-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicase-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicase-devel %{_description}

This package contains library source intended for building other packages which
use the "unicase" feature of the "%{crate}" crate.

%files       -n %{name}+unicase-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
