# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate icon-loader

Name:           rust-icon-loader
Version:        0.4.0
Release:        %autorelease
Summary:        To load and cache themed icons in 100% safe rust

License:        MIT
URL:            https://crates.io/crates/icon-loader
Source:         %{crates_source}

Patch0: downgrade-rust-ini.patch

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Crate to load and cache themed icons in 100% safe rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gtk-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gtk-devel %{_description}

This package contains library source intended for building other packages which
use the "gtk" feature of the "%{crate}" crate.

%files       -n %{name}+gtk-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+kde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+kde-devel %{_description}

This package contains library source intended for building other packages which
use the "kde" feature of the "%{crate}" crate.

%files       -n %{name}+kde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages which
use the "log" feature of the "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+theme_error_log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+theme_error_log-devel %{_description}

This package contains library source intended for building other packages which
use the "theme_error_log" feature of the "%{crate}" crate.

%files       -n %{name}+theme_error_log-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog

